import type { DartClass, DartField } from "./parser.js";

function fromJsonExpr(field: DartField): string {
  const { dartType: type, isNullable, jsonKey } = field;
  const key = `json['${jsonKey}']`;

  function castValue(t: string, expr: string, nullable: boolean): string {
    if (t === "dynamic") return expr;

    if (t === "String")
      return nullable ? `${expr} as String?` : `${expr} as String`;
    if (t === "bool") return nullable ? `${expr} as bool?` : `${expr} as bool`;
    if (t === "int") {
      return nullable
        ? `(${expr} as num?)?.toInt()`
        : `(${expr} as num).toInt()`;
    }

    if (t === "Map<String, dynamic>") {
      return nullable
        ? `${expr} != null ? Map<String, dynamic>.from(${expr} as Map) : null`
        : `Map<String, dynamic>.from(${expr} as Map)`;
    }

    if (t.startsWith("List<")) {
      const inner = t.slice(5, -1); // strip List< and >
      const innerClean = inner.endsWith("?") ? inner.slice(0, -1) : inner;
      let mapExpr: string;

      if (innerClean === "dynamic") {
        mapExpr = `List<dynamic>.from(${expr} as List)`;
      } else if (innerClean === "String" || innerClean === "bool") {
        mapExpr = `List<${innerClean}>.from(${expr} as List)`;
      } else if (innerClean === "int") {
        mapExpr = `(${expr} as List).map((e) => (e as num).toInt()).toList()`;
      } else if (innerClean === "Map<String, dynamic>") {
        mapExpr = `(${expr} as List).map((e) => Map<String, dynamic>.from(e as Map)).toList()`;
      } else {
        mapExpr = `(${expr} as List).map((e) => ${innerClean}.fromJson(e as Map<String, dynamic>)).toList()`;
      }

      return nullable ? `${expr} != null ? ${mapExpr} : null` : mapExpr;
    }

    // Reference type (Dart class)
    return nullable
      ? `${expr} != null ? ${t}.fromJson(${expr} as Map<String, dynamic>) : null`
      : `${t}.fromJson(${expr} as Map<String, dynamic>)`;
  }

  return castValue(type, key, isNullable);
}

function toJsonExpr(field: DartField): string {
  const { dartName: name, dartType: type, isNullable } = field;

  if (
    type === "dynamic" ||
    type === "String" ||
    type === "bool" ||
    type === "int" ||
    type === "Map<String, dynamic>"
  ) {
    return name;
  }

  if (type.startsWith("List<")) {
    const inner = type.slice(5, -1);
    const innerClean = inner.endsWith("?") ? inner.slice(0, -1) : inner;
    if (
      innerClean === "dynamic" ||
      innerClean === "String" ||
      innerClean === "int" ||
      innerClean === "bool" ||
      innerClean === "Map<String, dynamic>"
    ) {
      return name;
    }
    return isNullable
      ? `${name}?.map((e) => e.toJson()).toList()`
      : `${name}.map((e) => e.toJson()).toList()`;
  }

  // Reference type
  return isNullable ? `${name}?.toJson()` : `${name}.toJson()`;
}

function generateClass(cls: DartClass): string {
  const lines: string[] = [];

  lines.push(`class ${cls.name} {`);

  // Fields
  for (const f of cls.fields) {
    const typeStr = f.isNullable ? `${f.dartType}?` : f.dartType;
    lines.push(`  final ${typeStr} ${f.dartName};`);
  }
  lines.push("");

  // Constructor
  lines.push(`  const ${cls.name}({`);
  for (const f of cls.fields) {
    lines.push(
      f.isNullable
        ? `    this.${f.dartName},`
        : `    required this.${f.dartName},`,
    );
  }
  lines.push(`  });`);
  lines.push("");

  // fromJson factory
  lines.push(
    `  factory ${cls.name}.fromJson(Map<String, dynamic> json) => ${cls.name}(`,
  );
  for (const f of cls.fields) {
    lines.push(`    ${f.dartName}: ${fromJsonExpr(f)},`);
  }
  lines.push(`  );`);
  lines.push("");

  // toJson method
  lines.push(`  Map<String, dynamic> toJson() => {`);
  for (const f of cls.fields) {
    lines.push(`    '${f.jsonKey}': ${toJsonExpr(f)},`);
  }
  lines.push(`  };`);

  lines.push(`}`);

  return lines.join("\n");
}

export function generateDartFile(classes: DartClass[]): string {
  const lines: string[] = [
    "// GENERATED FILE — DO NOT EDIT BY HAND.",
    "// Generated by packages/type-bridge from Payload CMS types.",
    "// Run `pnpm generate` at the monorepo root to regenerate.",
    "",
    "// ignore_for_file: non_constant_identifier_names",
    "",
  ];

  for (const cls of classes) {
    lines.push(generateClass(cls));
    lines.push("");
  }

  return lines.join("\n");
}
