import 'package:news_blog/models/payload.dart';

const PostModel postTemplate = PostModel(
  id: 1,
  title: 'Test 1',
  media: {
    "id": 2,
    "alt": "test",
    "prefix": "public/media",
    "updatedAt": "2026-06-05T10:50:29.573Z",
    "createdAt": "2026-06-05T10:50:29.478Z",
    "url":
        "https://img.magnific.com/premium-photo/orange-galactic-spiral-cosmic-dance-stars-nebulae_1001175-36661.jpg",
    "thumbnailURL": null,
    "filename": "second.jpg",
    "mimeType": "image/jpeg",
    "filesize": 266589,
    "width": 1920,
    "height": 1080,
    "focalX": 50,
    "focalY": 50,

    "sizes": {
      "size_768": {
        "url":
            "https://img.magnific.com/premium-photo/orange-galactic-spiral-cosmic-dance-stars-nebulae_1001175-36661.jpg",
        "width": 768,
        "height": 432,
        "mimeType": "image/jpg",
        "filesize": 24416,
        "filename": "second-768x432.jpg",
      },

      "size_1024": {
        "url":
            "https://img.magnific.com/premium-photo/orange-galactic-spiral-cosmic-dance-stars-nebulae_1001175-36661.jpg",
        "width": 1024,
        "height": 576,
        "mimeType": "image/jpg",
        "filesize": 37498,
        "filename": "second-1024x576.jpg",
      },

      "size_1280": {
        "url":
            "https://img.magnific.com/premium-photo/orange-galactic-spiral-cosmic-dance-stars-nebulae_1001175-36661.jpg",
        "width": 1280,
        "height": 720,
        "mimeType": "image/jpg",
        "filesize": 53836,
        "filename": "second-1280x720.jpg",
      },

      "size_1440": {
        "url":
            "https://img.magnific.com/premium-photo/orange-galactic-spiral-cosmic-dance-stars-nebulae_1001175-36661.jpg",
        "width": 1400,
        "height": 788,
        "mimeType": "image/jpg",
        "filesize": 62428,
        "filename": "second-1400x788.jpg",
      },

      "size_1920": {
        "url":
            "https://img.magnific.com/premium-photo/orange-galactic-spiral-cosmic-dance-stars-nebulae_1001175-36661.jpg",
        "width": 1920,
        "height": 1080,
        "mimeType": "image/jpg",
        "filesize": 108360,
        "filename": "second-1920x1080.jpg",
      },

      "size_2560": {
        "url": null,
        "width": null,
        "height": null,
        "mimeType": null,
        "filesize": null,
        "filename": null,
      },
    },
  },
  content: {
    "root": {
      "type": "root",
      "format": "",
      "indent": 0,
      "version": 1,
      "children": [
        {
          "type": "paragraph",
          "format": "",
          "indent": 0,
          "version": 1,
          "children": [
            {
              "mode": "normal",
              "text": "test",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
          ],
          "direction": null,
          "textStyle": "",
          "textFormat": 0,
        },
        {
          "type": "paragraph",
          "format": "center",
          "indent": 0,
          "version": 1,
          "children": [
            {
              "mode": "normal",
              "text": "test",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
          ],
          "direction": null,
          "textStyle": "",
          "textFormat": 0,
        },
        {
          "type": "paragraph",
          "format": "right",
          "indent": 0,
          "version": 1,
          "children": [
            {
              "mode": "normal",
              "text": "test",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
          ],
          "direction": null,
          "textStyle": "",
          "textFormat": 0,
        },
        {
          "type": "paragraph",
          "format": "justify",
          "indent": 0,
          "version": 1,
          "children": [
            {
              "mode": "normal",
              "text": "test",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
          ],
          "direction": null,
          "textStyle": "",
          "textFormat": 0,
        },
        {
          "tag": "h5",
          "type": "heading",
          "format": "justify",
          "indent": 0,
          "version": 1,
          "children": [
            {
              "mode": "normal",
              "text": "h1",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
          ],
          "direction": null,
        },
        {
          "tag": "h2",
          "type": "heading",
          "format": "",
          "indent": 0,
          "version": 1,
          "children": [
            {
              "mode": "normal",
              "text": "h2",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
          ],
          "direction": null,
        },
        {
          "tag": "h3",
          "type": "heading",
          "format": "",
          "indent": 0,
          "version": 1,
          "children": [
            {
              "mode": "normal",
              "text": "h3",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
          ],
          "direction": null,
        },
        {
          "tag": "h4",
          "type": "heading",
          "format": "",
          "indent": 0,
          "version": 1,
          "children": [
            {
              "mode": "normal",
              "text": "h4",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
          ],
          "direction": null,
        },
        {
          "tag": "h5",
          "type": "heading",
          "format": "",
          "indent": 0,
          "version": 1,
          "children": [
            {
              "mode": "normal",
              "text": "h5",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
          ],
          "direction": null,
        },
        {
          "tag": "h5",
          "type": "heading",
          "format": "",
          "indent": 0,
          "version": 1,
          "children": [
            {
              "mode": "normal",
              "text": "h6",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
          ],
          "direction": null,
        },
        {
          "tag": "ul",
          "type": "list",
          "start": 1,
          "format": "",
          "indent": 0,
          "version": 1,
          "children": [
            {
              "type": "listitem",
              "value": 1,
              "format": "",
              "indent": 0,
              "checked": false,
              "version": 1,
              "children": [
                {
                  "mode": "normal",
                  "text": "Check",
                  "type": "text",
                  "style": "",
                  "detail": 0,
                  "format": 0,
                  "version": 1,
                },
              ],
              "direction": null,
            },
            {
              "type": "listitem",
              "value": 2,
              "format": "",
              "indent": 0,
              "checked": true,
              "version": 1,
              "children": [
                {
                  "mode": "normal",
                  "text": "check 2",
                  "type": "text",
                  "style": "",
                  "detail": 0,
                  "format": 0,
                  "version": 1,
                },
              ],
              "direction": null,
            },
            {
              "type": "listitem",
              "value": 3,
              "format": "",
              "indent": 0,
              "checked": false,
              "version": 1,
              "children": [
                {
                  "mode": "normal",
                  "text": "check 3",
                  "type": "text",
                  "style": "",
                  "detail": 0,
                  "format": 0,
                  "version": 1,
                },
              ],
              "direction": null,
            },
          ],
          "listType": "check",
          "direction": null,
        },
        {
          "tag": "ol",
          "type": "list",
          "start": 1,
          "format": "",
          "indent": 0,
          "version": 1,
          "children": [
            {
              "type": "listitem",
              "value": 1,
              "format": "",
              "indent": 0,
              "version": 1,
              "children": [
                {
                  "mode": "normal",
                  "text": "num 1",
                  "type": "text",
                  "style": "",
                  "detail": 0,
                  "format": 0,
                  "version": 1,
                },
              ],
              "direction": null,
            },
            {
              "type": "listitem",
              "value": 2,
              "format": "",
              "indent": 0,
              "version": 1,
              "children": [
                {
                  "mode": "normal",
                  "text": "num 2",
                  "type": "text",
                  "style": "",
                  "detail": 0,
                  "format": 0,
                  "version": 1,
                },
              ],
              "direction": null,
            },
            {
              "type": "listitem",
              "value": 3,
              "format": "",
              "indent": 0,
              "version": 1,
              "children": [
                {
                  "mode": "normal",
                  "text": "num 3",
                  "type": "text",
                  "style": "",
                  "detail": 0,
                  "format": 0,
                  "version": 1,
                },
              ],
              "direction": null,
            },
          ],
          "listType": "number",
          "direction": null,
        },
        {
          "tag": "ul",
          "type": "list",
          "start": 1,
          "format": "",
          "indent": 0,
          "version": 1,
          "children": [
            {
              "type": "listitem",
              "value": 1,
              "format": "",
              "indent": 0,
              "version": 1,
              "children": [
                {
                  "mode": "normal",
                  "text": "desc 1",
                  "type": "text",
                  "style": "",
                  "detail": 0,
                  "format": 0,
                  "version": 1,
                },
              ],
              "direction": null,
            },
            {
              "type": "listitem",
              "value": 2,
              "format": "",
              "indent": 0,
              "version": 1,
              "children": [
                {
                  "mode": "normal",
                  "text": "desc 2",
                  "type": "text",
                  "style": "",
                  "detail": 0,
                  "format": 0,
                  "version": 1,
                },
              ],
              "direction": null,
            },
            {
              "type": "listitem",
              "value": 3,
              "format": "",
              "indent": 0,
              "version": 1,
              "children": [
                {
                  "mode": "normal",
                  "text": "desc 3",
                  "type": "text",
                  "style": "",
                  "detail": 0,
                  "format": 0,
                  "version": 1,
                },
              ],
              "direction": null,
            },
          ],
          "listType": "bullet",
          "direction": null,
        },
        {"type": "horizontalrule", "version": 1},
        {
          "id": "6a26e37501617657396e9019",
          "type": "upload",
          "value": {
            "id": 1,
            "alt": "test",
            "prefix": "public/media",
            "updatedAt": "2026-06-02T10:46:20.424Z",
            "createdAt": "2026-06-02T10:46:20.352Z",
            "url":
                "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Red_circle.svg/1280px-Red_circle.svg.png",
            "thumbnailURL": null,
            "filename": "test.png",
            "mimeType": "image/png",
            "filesize": 46507,
            "width": 1280,
            "height": 1280,
            "focalX": 50,
            "focalY": 50,
            "sizes": {
              "size_768": {
                "url":
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Red_circle.svg/1280px-Red_circle.svg.png",
                "width": 768,
                "height": 768,
                "mimeType": "image/webp",
                "filesize": 27838,
                "filename": "test-768x768.webp",
              },
              "size_1024": {
                "url":
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Red_circle.svg/1280px-Red_circle.svg.png",
                "width": 1024,
                "height": 1024,
                "mimeType": "image/webp",
                "filesize": 39210,
                "filename": "test-1024x1024.webp",
              },
              "size_1280": {
                "url":
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Red_circle.svg/1280px-Red_circle.svg.png",
                "width": 1280,
                "height": 1280,
                "mimeType": "image/webp",
                "filesize": 33646,
                "filename": "test-1280x1280.webp",
              },
              "size_1440": {
                "url": null,
                "width": null,
                "height": null,
                "mimeType": null,
                "filesize": null,
                "filename": null,
              },
              "size_1920": {
                "url": null,
                "width": null,
                "height": null,
                "mimeType": null,
                "filesize": null,
                "filename": null,
              },
              "size_2560": {
                "url": null,
                "width": null,
                "height": null,
                "mimeType": null,
                "filesize": null,
                "filename": null,
              },
            },
          },
          "fields": null,
          "format": "",
          "version": 3,
          "relationTo": "media",
        },
        {
          "type": "paragraph",
          "format": "",
          "indent": 0,
          "version": 1,
          "children": [
            {
              "mode": "normal",
              "text": "test ",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
            {
              "id": "6a26e39201617657396e901a",
              "type": "link",
              "fields": {
                "url": "https://www.google.com",
                "newTab": true,
                "linkType": "custom",
              },
              "format": "",
              "indent": 0,
              "version": 3,
              "children": [
                {
                  "mode": "normal",
                  "text": "link",
                  "type": "text",
                  "style": "",
                  "detail": 0,
                  "format": 0,
                  "version": 1,
                },
              ],
              "direction": null,
            },
          ],
          "direction": null,
          "textStyle": "",
          "textFormat": 0,
        },
        {
          "type": "paragraph",
          "format": "",
          "indent": 0,
          "version": 1,
          "children": [
            {
              "mode": "normal",
              "text": "test ",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
            {
              "mode": "normal",
              "text": "bold",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 1,
              "version": 1,
            },
            {
              "mode": "normal",
              "text": ", ",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
            {
              "mode": "normal",
              "text": "italic",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 2,
              "version": 1,
            },
            {
              "mode": "normal",
              "text": ", ",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
            {
              "mode": "normal",
              "text": "underline",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 8,
              "version": 1,
            },
            {
              "mode": "normal",
              "text": ", ",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
            {
              "mode": "normal",
              "text": "test 2",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 4,
              "version": 1,
            },
            {
              "mode": "normal",
              "text": ", ",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
            {
              "mode": "normal",
              "text": "test 3",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 32,
              "version": 1,
            },
            {
              "mode": "normal",
              "text": ", ",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
            {
              "mode": "normal",
              "text": "test 4",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 64,
              "version": 1,
            },
            {
              "mode": "normal",
              "text": ", ",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 0,
              "version": 1,
            },
            {
              "mode": "normal",
              "text": "test 5",
              "type": "text",
              "style": "",
              "detail": 0,
              "format": 16,
              "version": 1,
            },
          ],
          "direction": null,
          "textStyle": "",
          "textFormat": 0,
        },
        {
          "type": "block",
          "fields": {
            "id": "6a2836f85fb2c4dbd691d0bd",
            "image": {
              "id": 2,
              "alt": "test",
              "prefix": "public/media",
              "updatedAt": "2026-06-05T10:50:29.573Z",
              "createdAt": "2026-06-05T10:50:29.478Z",
              "url":
                  "https://img.magnific.com/premium-photo/orange-galactic-spiral-cosmic-dance-stars-nebulae_1001175-36661.jpg",
              "thumbnailURL": null,
              "filename": "second.jpg",
              "mimeType": "image/jpeg",
              "filesize": 266589,
              "width": 1920,
              "height": 1080,
              "focalX": 50,
              "focalY": 50,
              "sizes": {
                "size_768": {
                  "url":
                      "https://img.magnific.com/premium-photo/orange-galactic-spiral-cosmic-dance-stars-nebulae_1001175-36661.jpg",
                  "width": 768,
                  "height": 432,
                  "mimeType": "image/webp",
                  "filesize": 24416,
                  "filename": "second-768x432.webp",
                },
                "size_1024": {
                  "url":
                      "https://img.magnific.com/premium-photo/orange-galactic-spiral-cosmic-dance-stars-nebulae_1001175-36661.jpg",
                  "width": 1024,
                  "height": 576,
                  "mimeType": "image/webp",
                  "filesize": 37498,
                  "filename": "second-1024x576.webp",
                },
                "size_1280": {
                  "url":
                      "https://img.magnific.com/premium-photo/orange-galactic-spiral-cosmic-dance-stars-nebulae_1001175-36661.jpg",
                  "width": 1280,
                  "height": 720,
                  "mimeType": "image/webp",
                  "filesize": 53836,
                  "filename": "second-1280x720.webp",
                },
                "size_1440": {
                  "url":
                      "https://img.magnific.com/premium-photo/orange-galactic-spiral-cosmic-dance-stars-nebulae_1001175-36661.jpg",
                  "width": 1400,
                  "height": 788,
                  "mimeType": "image/webp",
                  "filesize": 62428,
                  "filename": "second-1400x788.webp",
                },
                "size_1920": {
                  "url":
                      "https://img.magnific.com/premium-photo/orange-galactic-spiral-cosmic-dance-stars-nebulae_1001175-36661.jpg",
                  "width": 1920,
                  "height": 1080,
                  "mimeType": "image/webp",
                  "filesize": 108360,
                  "filename": "second-1920x1080.webp",
                },
                "size_2560": {
                  "url": null,
                  "width": null,
                  "height": null,
                  "mimeType": null,
                  "filesize": null,
                  "filename": null,
                },
              },
            },
            "blockName": "",
            "blockType": "image-with-aspect-ratio",
            "aspectRatio": "1/1",
          },
          "format": "",
          "version": 2,
        },
        {
          "type": "paragraph",
          "format": "",
          "indent": 0,
          "version": 1,
          "children": [],
          "direction": null,
          "textStyle": "",
          "textFormat": 0,
        },
      ],
      "direction": null,
    },
  },
  updatedAt: '2026-06-09T16:31:02.097Z',
  createdAt: '2026-06-09T16:31:02.097Z',
);

const List<PostModel> postsTemplate = [postTemplate];
