// GENERATED FILE — DO NOT EDIT BY HAND.
// Generated by packages/type-bridge from Payload CMS types.
// Run `pnpm generate` at the monorepo root to regenerate.

// ignore_for_file: non_constant_identifier_names

class User {
  final int id;
  final String updatedAt;
  final String createdAt;
  final bool? enableAPIKey;
  final String? apiKey;
  final String? apiKeyIndex;
  final String email;
  final String? resetPasswordToken;
  final String? resetPasswordExpiration;
  final String? salt;
  final String? hash;
  final int? loginAttempts;
  final String? lockUntil;
  final List<Map<String, dynamic>>? sessions;
  final String? password;
  final String collection;

  const User({
    required this.id,
    required this.updatedAt,
    required this.createdAt,
    this.enableAPIKey,
    this.apiKey,
    this.apiKeyIndex,
    required this.email,
    this.resetPasswordToken,
    this.resetPasswordExpiration,
    this.salt,
    this.hash,
    this.loginAttempts,
    this.lockUntil,
    this.sessions,
    this.password,
    required this.collection,
  });

  factory User.fromJson(Map<String, dynamic> json) => User(
    id: (json['id'] as num).toInt(),
    updatedAt: json['updatedAt'] as String,
    createdAt: json['createdAt'] as String,
    enableAPIKey: json['enableAPIKey'] as bool?,
    apiKey: json['apiKey'] as String?,
    apiKeyIndex: json['apiKeyIndex'] as String?,
    email: json['email'] as String,
    resetPasswordToken: json['resetPasswordToken'] as String?,
    resetPasswordExpiration: json['resetPasswordExpiration'] as String?,
    salt: json['salt'] as String?,
    hash: json['hash'] as String?,
    loginAttempts: (json['loginAttempts'] as num?)?.toInt(),
    lockUntil: json['lockUntil'] as String?,
    sessions: json['sessions'] != null ? (json['sessions'] as List).map((e) => Map<String, dynamic>.from(e as Map)).toList() : null,
    password: json['password'] as String?,
    collection: json['collection'] as String,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'updatedAt': updatedAt,
    'createdAt': createdAt,
    'enableAPIKey': enableAPIKey,
    'apiKey': apiKey,
    'apiKeyIndex': apiKeyIndex,
    'email': email,
    'resetPasswordToken': resetPasswordToken,
    'resetPasswordExpiration': resetPasswordExpiration,
    'salt': salt,
    'hash': hash,
    'loginAttempts': loginAttempts,
    'lockUntil': lockUntil,
    'sessions': sessions,
    'password': password,
    'collection': collection,
  };
}

class Media {
  final int id;
  final String alt;
  final String? prefix;
  final String updatedAt;
  final String createdAt;
  final String? url;
  final String? thumbnailURL;
  final String? filename;
  final String? mimeType;
  final int? filesize;
  final int? width;
  final int? height;
  final int? focalX;
  final int? focalY;
  final Map<String, dynamic>? sizes;

  const Media({
    required this.id,
    required this.alt,
    this.prefix,
    required this.updatedAt,
    required this.createdAt,
    this.url,
    this.thumbnailURL,
    this.filename,
    this.mimeType,
    this.filesize,
    this.width,
    this.height,
    this.focalX,
    this.focalY,
    this.sizes,
  });

  factory Media.fromJson(Map<String, dynamic> json) => Media(
    id: (json['id'] as num).toInt(),
    alt: json['alt'] as String,
    prefix: json['prefix'] as String?,
    updatedAt: json['updatedAt'] as String,
    createdAt: json['createdAt'] as String,
    url: json['url'] as String?,
    thumbnailURL: json['thumbnailURL'] as String?,
    filename: json['filename'] as String?,
    mimeType: json['mimeType'] as String?,
    filesize: (json['filesize'] as num?)?.toInt(),
    width: (json['width'] as num?)?.toInt(),
    height: (json['height'] as num?)?.toInt(),
    focalX: (json['focalX'] as num?)?.toInt(),
    focalY: (json['focalY'] as num?)?.toInt(),
    sizes: json['sizes'] != null ? Map<String, dynamic>.from(json['sizes'] as Map) : null,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'alt': alt,
    'prefix': prefix,
    'updatedAt': updatedAt,
    'createdAt': createdAt,
    'url': url,
    'thumbnailURL': thumbnailURL,
    'filename': filename,
    'mimeType': mimeType,
    'filesize': filesize,
    'width': width,
    'height': height,
    'focalX': focalX,
    'focalY': focalY,
    'sizes': sizes,
  };
}

class Page {
  final int id;
  final String title;
  final dynamic media;
  final String updatedAt;
  final String createdAt;

  const Page({
    required this.id,
    required this.title,
    required this.media,
    required this.updatedAt,
    required this.createdAt,
  });

  factory Page.fromJson(Map<String, dynamic> json) => Page(
    id: (json['id'] as num).toInt(),
    title: json['title'] as String,
    media: json['media'],
    updatedAt: json['updatedAt'] as String,
    createdAt: json['createdAt'] as String,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'title': title,
    'media': media,
    'updatedAt': updatedAt,
    'createdAt': createdAt,
  };
}

class PayloadKv {
  final int id;
  final String key;
  final dynamic? data;

  const PayloadKv({
    required this.id,
    required this.key,
    this.data,
  });

  factory PayloadKv.fromJson(Map<String, dynamic> json) => PayloadKv(
    id: (json['id'] as num).toInt(),
    key: json['key'] as String,
    data: json['data'],
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'key': key,
    'data': data,
  };
}

class PayloadLockedDocument {
  final int id;
  final dynamic? document;
  final String? globalSlug;
  final Map<String, dynamic> user;
  final String updatedAt;
  final String createdAt;

  const PayloadLockedDocument({
    required this.id,
    this.document,
    this.globalSlug,
    required this.user,
    required this.updatedAt,
    required this.createdAt,
  });

  factory PayloadLockedDocument.fromJson(Map<String, dynamic> json) => PayloadLockedDocument(
    id: (json['id'] as num).toInt(),
    document: json['document'],
    globalSlug: json['globalSlug'] as String?,
    user: Map<String, dynamic>.from(json['user'] as Map),
    updatedAt: json['updatedAt'] as String,
    createdAt: json['createdAt'] as String,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'document': document,
    'globalSlug': globalSlug,
    'user': user,
    'updatedAt': updatedAt,
    'createdAt': createdAt,
  };
}

class PayloadPreference {
  final int id;
  final Map<String, dynamic> user;
  final String? key;
  final dynamic? value;
  final String updatedAt;
  final String createdAt;

  const PayloadPreference({
    required this.id,
    required this.user,
    this.key,
    this.value,
    required this.updatedAt,
    required this.createdAt,
  });

  factory PayloadPreference.fromJson(Map<String, dynamic> json) => PayloadPreference(
    id: (json['id'] as num).toInt(),
    user: Map<String, dynamic>.from(json['user'] as Map),
    key: json['key'] as String?,
    value: json['value'],
    updatedAt: json['updatedAt'] as String,
    createdAt: json['createdAt'] as String,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'user': user,
    'key': key,
    'value': value,
    'updatedAt': updatedAt,
    'createdAt': createdAt,
  };
}

class PayloadMigration {
  final int id;
  final String? name;
  final int? batch;
  final String updatedAt;
  final String createdAt;

  const PayloadMigration({
    required this.id,
    this.name,
    this.batch,
    required this.updatedAt,
    required this.createdAt,
  });

  factory PayloadMigration.fromJson(Map<String, dynamic> json) => PayloadMigration(
    id: (json['id'] as num).toInt(),
    name: json['name'] as String?,
    batch: (json['batch'] as num?)?.toInt(),
    updatedAt: json['updatedAt'] as String,
    createdAt: json['createdAt'] as String,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'name': name,
    'batch': batch,
    'updatedAt': updatedAt,
    'createdAt': createdAt,
  };
}
